#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Quit,
    MoveSelection(i32),
    Insert(char),
    Backspace,
    DeleteWord,
    CursorLeft,
    CursorRight,
    ClearQuery,
    OpenRepo,
    OpenBranches,
    OpenBranch,
    StartNewBranch,
    CreateNewBranch,
    DeleteWorktree,
    ConfirmDeleteWorktree,
    CancelOverlay,
    BackToRepos,
    DismissToast,
    ShowHelp,
    CloseHelp,
    Noop,
}
